spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usama_sms?createDatabaseIfNotExist=true
    username: root
    password: 12345
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: Create