spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usama_sms?createDatabaseIfNotExist=true
    username: root
    password: 1qaz2wsx@
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
  security:
    oauth2:
      client:
        client-id: web
        client-secret: web
      resource:
        token-info-uri: http://localhots:8082/outh/check_token
     
       